
import "./globals.css";
import Navbar from "./(components)/(common)/nav/pages";
import Footer from "./(components)/(common)/footer/page";


import { Roboto } from "next/font/google";
const roboto=Roboto({
  subsets:['latin'],
  weight:['400','700']
})
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={roboto.className}>
       <Navbar/>
        {children}
        <Footer/>

        </body>
    </html>
  );
}
